### ISSUE TITLE
common.h make pi

### ISSUE THREAD

**Issue by noppelmax** [larsmm/pixelflut#9]
Hey larsmm,

i tried to compile the projekt on a pi and get the error of a not found common.h.

```
gcc -c -O3 -march=native -DUSE_OPENGL -DUSE_EGL -DIS_RPI -DSTANDALONE -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -D_LINUX -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -Wall -DHAVE_LIBOPENMAX=2 -DOMX -DOMX_SKIP64BIT -ftree-vectorize -pipe -DUSE_EXTERNAL_OMX -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DUSE_VCHIQ_ARM -Wno-psabi -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -I./ -I/opt/vc/src/hello_pi/libs/ilclient -I/opt/vc/src/hello_pi/libs/vgfont -Wno-deprecated-declarations -Wno-missing-braces -fomit-frame-pointer main_pi.c -o main_pi.o
main_pi.c:1:20: fatal error: common.c: No such file or directory
 #include "common.c"
                    ^
compilation terminated.
Makefile:18: recipe for target 'main_pi.o' failed
make: *** [main_pi.o] Error 1
```

Could you please give a hint what i could try? I tried by commenting out the include but it is not working.

Greez,
nopx

**Comment by larsmm** [comment]
please try again and tell if it is working now.
https://github.com/larsmm/pixelflut/commit/c941274265773d2cb5afc0f622ab0058604cfcd9

maybe you want stronger hardware. sdl version does have more features.

**Comment by noppelmax** [comment]
Hey, thanks. I tried to compile it. It is not finding PIXEL_WIDTH, PIXEL_HEIGHT and CONNECTION_TIMEOUT. I set em to 1920, 1080 and 2. It compiles now but is not showing anything. Do you have any further ideas what the problem may be?
Regards,
Max

**Comment by larsmm** [comment]
This is the last version before refactoring. Please try that: https://github.com/larsmm/pixelflut/commit/7ba726b50f587a61c2ed046fe85c6ab3372d7e81

**Comment by larsmm** [comment]
It is now working on newest Raspbian :-)
You get around 30-35 megabytes/s on a Raspberry Pi 4B.
